services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - cryoet_data:/var/lib/postgresql/data

  vault:
    image: hashicorp/vault:1.15.2
    restart: always
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
    cap_add:
      - IPC_LOCK

  app:
    build: .
    depends_on:
      - db
      - vault
    environment:
      # Адрес Vault и токен
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
      # Хост БД
      - DB_HOST=db
      # *** ДОБАВЛЕННЫЙ БЛОК ДЛЯ ИНИЦИАЛИЗАЦИИ VAULT ***
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data:/app/data
      - ./output:/app/output

volumes:
  cryoet_data: